# Generated by Django 5.1.3 on 2024-11-21 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
        ('transferencia_motivo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='transferencia_motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transferencia_motivo.motivotransferencia'),
        ),
    ]
