<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-11-18 20:30
=======
# Generated by Django 5.1.3 on 2024-11-18 16:14
>>>>>>> 1b04dc77a82d3c26319ab5bc9c4097a014ee695e

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
=======
                ('descripcion', models.CharField(max_length=255, unique=True)),
>>>>>>> 1b04dc77a82d3c26319ab5bc9c4097a014ee695e
            ],
        ),
    ]
